stages:
  - test
  - package

variables:
  RESULTS_DIR: results

# Étape 1 : Exécution des tests Robot Framework
robot_tests:
  stage: test
  image: python:3.11
  before_script:
    - pip install -r requirements.txt
  script:
    - echo "Exécution des tests Robot Framework..."
    - robot -d ${RESULTS_DIR} tests/
  artifacts:
    when: always
    paths:
      - ${RESULTS_DIR}/
    reports:
      junit: ${RESULTS_DIR}/output.xml

# Étape 2 : Archivage des résultats
package_results:
  stage: package
  image: python:3.11
  before_script:
    - apt-get update && apt-get install -y zip
  script:
    - echo "Création de l'archive des résultats..."
    - zip -r robot-results.zip results/
  artifacts:
    paths:
      - robot-results.zip
