stages:
  - test

variables:
  ROBOT_OPTIONS: "--outputdir reports --report report.html --log log.html --console verbose"

robot_tests:
  image: python:3.12
  stage: test
  before_script:
    - pip install --upgrade pip
    - pip install -r requirements.txt
    - apt-get update && apt-get install -y xvfb unzip wget
    - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    - apt install -y ./google-chrome-stable_current_amd64.deb
  script:
    - xvfb-run robot $ROBOT_OPTIONS tests/
  artifacts:
    paths:
      - reports/
    expire_in: 1 week
