stages:
  - test

variables:
  ROBOT_OUTPUT_DIR: "resultats/preprod"

robot-tests:
  image: python:3.11
  stage: test
  before_script:
    - apt-get update && apt-get install -y wget unzip xvfb libnss3 libgconf-2-4 fonts-liberation libxss1 libappindicator3-1 libatk-bridge2.0-0 libgtk-3-0
    - wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | apt-key add -
    - sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
    - apt-get update && apt-get install -y google-chrome-stable
    - CHROME_VERSION=$(google-chrome --version | grep -oP "\d+" | head -1)
    - wget -O /tmp/chromedriver.zip https://chromedriver.storage.googleapis.com/${CHROME_VERSION}.0/chromedriver_linux64.zip
    - unzip /tmp/chromedriver.zip -d /usr/local/bin/
    - chmod +x /usr/local/bin/chromedriver
    - pip install --upgrade pip
    - pip install robotframework==7.3.2 robotframework-seleniumlibrary selenium
    - mkdir -p $ROBOT_OUTPUT_DIR
  script:
    - robot --variable ENV:preprod --outputdir $ROBOT_OUTPUT_DIR tests/
  artifacts:
    paths:
      - $ROBOT_OUTPUT_DIR/output.xml
      - $ROBOT_OUTPUT_DIR/log.html
      - $ROBOT_OUTPUT_DIR/report.html
    expire_in: 1 week
